version: "3.9"

# Tek servis: Nginx ile frontend static yayÄ±n
services:
  cronbi-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cronbi-frontend
    ports:
      - "80:80"
    restart: unless-stopped
